### ISSUE TITLE
[FEATURE REQUEST] Полное ФИО преподавателей

### ISSUE THREAD

**Issue by RomanSoloweow** [Ninja-Official/rtu-mirea-mobile#102]
Однозначно нужно полное ФИО. Мне рассказывали почему это сложно (есть однофамильцы с одинаковыми инициалами). Но где это возможно было бы круто сделать.

**Comment by 0niel** [comment]
У нас расписание парсится исключительно из документов с расписанием с официального сайта. Нам руководство университета не давало доступа ни к каким базам и т.п. вещам. В документах ФИО преподавателей пишется в формате "Фамилия И.О.", так что пока что полное ФИО реализовать не представляется возможным.

**Comment by 0niel** [comment]
Теперь реализован полноценный поиск преподавателей по фамилии (#109). Там можно и посмотреть краткую сводку о преподавателе, например, должность и занимаемые ставки. Полное ФИО в расписании лишнее. 

Возможно нужно будет сделать ФИО в расписании в виде какой-то ссылки, по нажатию на котороую будет открываться страница с информацией о преподавателе, но это в будущем.
