### ISSUE TITLE
[FEATURE REQUEST] Информация о преподавателе

### ISSUE THREAD

**Issue by RomanSoloweow** [Ninja-Official/rtu-mirea-mobile#103]
Возможно, в будущем туда можно будет добавить расписание конкретного преподавателя.
Пока что предлагаю добавить почту, хотя бы корпоративную. Чтоб можно было связаться, а не искать контакты в гугле

**Comment by 0niel** [comment]
Но а где нам найти почту преподавателя? В документах с расписанием почту не пишут. Как нам однозначно сопоставить ФИО преподавателя и его почту?

**Comment by RomanSoloweow** [comment]
Я тама в телегу вашу написал. Напиши в лс)

**Comment by 0niel** [comment]
Реализовано в #109
