### ISSUE TITLE
[BUG] Ошибка загрузки патронов

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#122]
**Описание ошибки**
Ошибка загрузки раздела Патроны

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейти в раздел «Профиль»
2. Нажать на кнопку «О приложении»
3. См. ошибку

**Ожидаемое поведение**
Иконки с патронами

**Скриншоты**
![064529C7-9FFC-40B0-97C7-A295CCAFA9A1](https://user-images.githubusercontent.com/70258211/147400986-61d1f3ae-a4fe-45d1-b157-a5d539bbe8dc.jpeg)

**Смартфон**
 - Девайс: iPad
 - OS: iPadOS

**Comment by 0niel** [comment]
Исправлено в #128
