### ISSUE TITLE
[FEATURE REQUEST] Электронный студенческий билет

### ISSUE THREAD

**Issue by SyntOwl** [Ninja-Official/rtu-mirea-mobile#132]
Возможность использования телефона как студенческого билета.
Пример: На входе в институт нужно достать студ. билет, приложить его к считывателю, после опять убрать. А если ты забыл студ. билет то это ещё больший геморой.

Добавить возможность конвертации студ. билета в электронную версию по средствам считывания данных с метки в студ. билете или через оф сайт института.
Добавить для телефонов с NFC возможность использования его как пропуска.

Можно сэкономить время людей и ускорить вход в институт при большой нагрузке людей.

**Comment by 0niel** [comment]
Идея очень классная, но реализовать технически это невозможно по многим причинам, по крайней мере сейчас.
