### ISSUE TITLE
[BUG] Итоги TestFlight для 1.2.0

### ISSUE THREAD

**Issue by 0niel** [Ninja-Official/rtu-mirea-mobile#139]
**Описание ошибок**

- [x] BottomNavigationBar на странице профиля слишком большой.
- [x] У BottomNavigationBar нет SafeArea. Элементы операционной системы заходят на интерфейс.
- [x] Иногда на странице расписания не всплывает модальное окно с выбором группы.
- [x] Если пролистнуть список новостей до конца, то происходи полное обновление новостей, а список тегов сбрасывается.
- [x] В сторис картинка большого размера грузится слишком долго. Нужно загружать среднюю.
- [x] Всплывающее окно при копировании текста на странице деталей профиля слишком большое.
- [x] На странице посещаемости под текстом о кол-во песещенных дней нет отступа.
- [x] У важных новостей нет тегов, но иконка с тегами все равно отображается.
- [x] На странице входа конпка входа перекрыта какими-то элементами, из-за этого она не работает.
- [x] На странице профиля в объявлениях не работают ссылки и текст не копируется.
- [x] Теги на странице новостей не имеют эффекта нажатия.
- [x] CircularProgressIndicator на странице профиля находится не по центру при первой загрузке.
- [x] Если текущий день не входит в промежуток дней, установленных в календаре расписания (за рамками семестра), то у календаря странное поведение. 

**Смартфон:**
 - Девайс: iPhone 13
 - OS: iOS 15.3

**Comment by 0niel** [comment]
Всем спасибо, все свободны.

**Comment by Dragonprod** [comment]
Спидран прошёл успешно.
