### ISSUE TITLE
[BUG] Картинки новостей низкого разрешения

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#154]
**Описание ошибки**
Картинки в ленте новостей имеют низкое разрешение.

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейдите в раздел «Новости»
2. См. ошибку

**Ожидаемое поведение**
Разборчивые картинки

**Скриншот**
![IMG_2540](https://user-images.githubusercontent.com/70258211/151969224-234413ab-5e24-4516-8c0f-0c2ca65492a4.png)
![IMG_2541](https://user-images.githubusercontent.com/70258211/151969718-a1409a49-97b6-4008-8988-75b85337e73a.png)

**Смартфон:**
 - Девайс: iPad
 - OS: iPadOS 14.3

**Comment by 0niel** [comment]
Исправлено в #176
