### ISSUE TITLE
[BUG] Некорректное удаление символов при выборе группы

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#155]
**Описание ошибки**
При нажатии на кнопку «удалить» в графе выбора группы удаляется одновременно первый и последний символ.

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейти в раздел «Управление расписанием и группами»
2. Кликнуть в «Добавить группу»
3. Ввести символы «ABCD-EF-GH»
4. Попытаться удалить последний символ
5. См. поле «BCDE-FG»
6. Попытаться удалить последний символ
7. См. поле «CDEF»
8. Попытаться удалить последний символ
9. См. поле «DE»

Дальнейшие попытки удаления символов корректны.

**Ожидаемое поведение**
Удаление одного символа перед курсором.

**Смартфон:**
 - Девайс: iPad
 - OS: iPadOS 14.3

**Comment by 0niel** [comment]
Спасибо. Исправлено в #189
