### ISSUE TITLE
[BUG] Оторванный текст от кнопки выбора периода посещаемости

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#156]
**Описание ошибки**
Текст «Промежуток:» находится далеко от кнопки с выбором периода. 

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейдите в «Профиль»
2. Перейти в «Посещаемость»
3. См. ошибку

**Ожидаемое поведение**
Текст в контексте кнопки.

**Скриншоты**
![AE2D131F-EF95-4C46-83CB-406841665B04](https://user-images.githubusercontent.com/70258211/151987345-5da82277-8133-4422-a21c-3f87c277a7e3.jpeg)

**Смартфон:**
 - Девайс: iPad
 - OS: iPadOS 14.3

**Comment by 0niel** [comment]
Исправлено в #179
