### ISSUE TITLE
[BUG] Серый экран при нажатии на кнопку выбора тега 

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#158]
**Описание ошибки**
Если нажать на кнопку выбора тега во время существующей загрузки появляется серый экран.

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейти в раздел «Новости»
2. Выбрать тег
3. Успеть во время загрузки предыдущего запроса нажать на кнопку выбора тега еще раз
4. См ошибку

**Ожидаемое поведение**
Отображение панели с выбором тега.

**Скриншоты**
![IMG_2545](https://user-images.githubusercontent.com/70258211/151989114-6bd80885-36ed-48ec-b002-cb51f73abf5a.png)

**Смартфон:**
 - Девайс: iPad
 - OS: iPadOS 14.3

**Comment by 0niel** [comment]
Проблема была вызвана исключением из-за картинки неправильного формата. Исправлено в #176

**Comment by 0niel** [comment]
Спасибо. Исправлено в #190
