### ISSUE TITLE
[BUG] Отображение расписания в iOS виджете за пределами семестра

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#161]
**Описание ошибки**
Отсутствуют границы семестра в iOS виджетах, из-за чего появляется расписание в день вне семестра

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Установить системную дату, недоступную в расписании в приложении (за пределами семестра)
2. Открыть виджет
3. См. ошибку

**Ожидаемое поведение**
Заглушка «День вне семестра»

**Смартфон:**
 - Девайс: iPadOS
 - OS: iPadOS 14.3

**Comment by ValeryVerkhoturov** [comment]
Дубликат #160

**Comment by L3odr0id** [comment]
Решено в #157
