### ISSUE TITLE
[BUG] Серый экран при открытии статьи в разделе «Новости»

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#162]
**Описание ошибки**
При открытии определенной новостной статьи появляется серый экран.

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейти в раздел «Новости»
2. Открыть статью с названием «Институт информационных технологий внедряет в учебный процесс систему управления процессом разработки программного обеспечения «Devprom»»
3. См. ошибку

**Ожидаемое поведение**
При открытии статьи появляется картинка и текст.

**Скриншоты**
![IMG_2552](https://user-images.githubusercontent.com/70258211/152104247-49e632f3-aca2-40ee-9021-41339ff10498.png)

**Смартфон:**
 - Девайс: iPad
 - OS: iPadOS 14.3

**Дополнительно**
Оригинальная статья - https://www.mirea.ru/news/institut-informatsionnykh-tekhnologiy-vnedryaet-v-uchebnyy-protsess-sistemu-upravleniya-protsessom-r/.

Аналогичная проблема в:
* https://www.mirea.ru/news/institut-informatsionnykh-tekhnologiy-rasshiryaet-uchastie-v-sap-university-alliance/
* https://www.mirea.ru/news/studenty-rtu-mirea-vyshli-v-final-evraziyskikh-sorevnovaniy-huawei-cup-2021/
* https://www.mirea.ru/news/prepodavatelyu-kolledzha-rtu-mirea-prisvoena-vysshaya-kvalifikatsionnaya-kategoriya-prepodavatel/
* https://www.mirea.ru/news/v-rtu-mirea-startuet-superfinal-rdr-2020-21/
* https://www.mirea.ru/news/kruzhok-kreativnaya-ekonomika-organizoval-diskussiyu-o-narodnykh-predpriyatiyakh/

Возможно имеет связь с #158.

**Comment by 0niel** [comment]
Проблема была вызвана исключением из-за картинки неправильного формата. Исправлено в https://github.com/Ninja-Official/rtu-mirea-mobile/pull/176
