### ISSUE TITLE
[BUG] Движение поля ввода фамилии в альбомной ориентации в разделе «Преподаватели» 

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#164]
**Описание ошибки**
При нажатии на поле ввода  в разделе «Преподаватели» меняется его местоположение с левого края в середину в альбомной ориентации. В книжной ориентации поле ввода статично посередине.

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейти в раздел «Профиль»
2. Перейти в раздел «Преподаватели»
3. В альбомной ориентации кликнуть на поле ввода фамилии
4. См. ошибку

**Ожидаемое поведение**
Статичное положение поля ввода независимо от ориентации приложения.

**Скриншоты**
![IMG_2557](https://user-images.githubusercontent.com/70258211/152356951-66febeef-8caf-4772-80f0-335336ffdd77.png)
![IMG_2558](https://user-images.githubusercontent.com/70258211/152356959-fc678079-448f-49c5-b9df-ddd975386bfb.png)

**Смартфон:**
 - Девайс: iPad
 - OS: iPadOS 14.3

**Comment by 0niel** [comment]
Спасибо. Исправлено в #187
