### ISSUE TITLE
[BUG] Некорректное отображение аватара в профиле

### ISSUE THREAD

**Issue by TinyClayMan** [Ninja-Official/rtu-mirea-mobile#167]
**Описание ошибки**
На странице профиля аватар отображается с частично обрезанной кнопкой "Загрузить фото".

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейти в раздел профиля
2. Войти в профиль
3. Смотреть на некорректное отображение

**Ожидаемое поведение**
Круглый аватар в приложении должен соответствовать круглому аватару с сайта.

**Скриншоты**
![avatarBug](https://user-images.githubusercontent.com/70881505/152414215-52d2078b-dad6-4b41-8148-76a50a03da5a.png)

**Смартфон:**
 - Устройства: Samsung Galaxy Note 10+, Samsung Galaxy S8

**Comment by 0niel** [comment]
@TinyClayMan, можешь ли ты скопировать эту картинку с ЛКС и скинуть сюда?

**Comment by TinyClayMan** [comment]
Попробовал это сделать:
Оказывается, это проблема со стороны МИРЭА. 
Файл доступен по публичной [ссылке](https://lk.mirea.ru/upload/main/66b/%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C_%D1%84%D0%BE%D1%82%D0%BE.png), и приложение парсит его корректно.

Возможно, стоит прописать правило для файлов аватаров, имеющих название "загрузить_фото.png". И либо заменять их на нормальный (обрезанный) файл, либо вставлять свою заглушку.

**Comment by TinyClayMan** [comment]
Оказалось, всё работает нормально. Бага нет.

**Comment by ValeryVerkhoturov** [comment]
ЛКС обрезает низ, приложение обрезает верх.

**Comment by ValeryVerkhoturov** [comment]
@TinyClayMan сделай скриншот из ЛКС, пожалуйста.
