### ISSUE TITLE
[BUG] Открываются «Карты» при сдвиге истории

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#171]
**Описание ошибки**
Если историю сдвинуть (вверх/вниз) и удерживать не в стандартном положении, то после истечения таймера открывается раздел «Карты».

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейти в раздел «Новости»
2. Кликнуть на историю
3. Сдвинуть историю вниз и не отпускать нажатие
4. Дождаться момента закрытия истории
5. См. переход в раздел «Карты»

**Ожидаемое поведение**
После закрытия истории продолжать находиться в разделе «Новости».

**Смартфон:**
 - Девайс: iPad
 - OS: iPadOS 14.3

**Comment by 0niel** [comment]
Исправлено в #177
