### ISSUE TITLE
[BUG] Не работает виджет на раб. столе

### ISSUE THREAD

**Issue by lexa-makeev** [Ninja-Official/rtu-mirea-mobile#172]
**Описание ошибки**
Не работает виджет на рабочем столе мобильного устройства. До сих пор на виджет написано"сессия..."

**Ожидаемое поведение**
Расписание на текущий день.

**Смартфон (пожалуйста, заполните следующую информацию):**
 - Девайс: Realme 8i
 - OS: realme ui v2.0

**Comment by L3odr0id** [comment]
Решено в #173
