### ISSUE TITLE
[FEATURE REQUEST] Изменение цветов на карте

### ISSUE THREAD

**Issue by 0niel** [Ninja-Official/rtu-mirea-mobile#37]
Цвета на карте слишком контрастные, а особенно выделяется ненужные пространства из белого цвета. Необходимо изменить цвета. 

![Screenshot_2021-08-25-23-50-00-903_ninja mirea mireaapp](https://user-images.githubusercontent.com/51058739/130862953-2e51501f-41ca-4e24-bca4-af0f27a18dc2.jpg)

**Comment by ValeryVerkhoturov** [comment]
Заполнить пространства диагональными линиями и покрасить цветом нижней панели
![421A4C59-B6F7-4A71-AA6B-61600BC0BC35](https://user-images.githubusercontent.com/70258211/131254088-cf595350-575a-42d0-88e7-e694eb2e1b78.png)

**Comment by ValeryVerkhoturov** [comment]
Неактивные зоны заполнить цветом нижней панели, заполнить косыми линиями (см картинку) цвета неактивных иконок.
![649E4391-EC89-436C-959D-09F09EAF6E97](https://user-images.githubusercontent.com/70258211/131254351-a07f5d73-074c-4928-a23d-1a56375f368b.jpeg)

**Comment by ValeryVerkhoturov** [comment]
Хотя цвета нужно целиком переработать

**Comment by ValeryVerkhoturov** [comment]
Цвет туалетов на 4 этаже отличается от цвета на других этажах

**Comment by Sn0wy-0wl** [comment]
@ValeryVerkhoturov просто бог
