### ISSUE TITLE
[FEATURE REQUEST] Добавить виджеты рабочего стола для Android и iOS

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#40]
![8828B012-0823-47F2-A485-E4D8295BFE1B](https://user-images.githubusercontent.com/70258211/130936328-e657f786-5a0e-486f-bf0a-04f6e63833b6.jpeg)
![A74E3F67-B589-407E-A14C-FFE1951CD2CB](https://user-images.githubusercontent.com/70258211/130936782-3a6c6edd-7bb8-4da7-8d60-625927fb7219.jpeg)
![BEA4B858-07F1-457F-9049-C08154D05DD8](https://user-images.githubusercontent.com/70258211/130936817-70b84351-31ee-40ae-8dd9-57d80b76bcba.jpeg)

**Comment by ValeryVerkhoturov** [comment]
![1FF8BA05-8B2A-4DD9-BC11-FD5D5B194A42](https://user-images.githubusercontent.com/70258211/131254620-7ce64226-99f3-4526-89da-7002808c5724.jpeg)

**Comment by 0niel** [comment]
Реализовано @L3odr0id  в #117
