### ISSUE TITLE
[FEATURE REQUEST] Возврат стандартного размера карты, ограничение масштабирования

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#55]
**Текущая реализация**
Возможность уменьшать карту до полного исчезновения, увеличивать до нечитабельного состояния. Лечится масштаб при повторном заходе в раздел.

**Решение**
Показывать текущий % масштабирования. При нажатии на число возвращать оригинальный масштаб.

**Дополнительно**
Ограничить возможности масштабирования.

**Comment by 0niel** [comment]
Реализовано в #64. Спасибо @Sn0wy-0wl
