### ISSUE TITLE
[QUESTION] Обновление расписания

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#57]
Попытка обновить расписание происходит при каждом запуске приложения?

**Comment by 0niel** [comment]
Да, расписание обновляется при каждом запуске. Если интернета нет, то берётся из локального хранилища

**Comment by ValeryVerkhoturov** [comment]
Нужно ненавязчиво, но понятно обозначить. Не знаю как.
