### ISSUE TITLE
[FEATURE REQUEST] Оптимизировать ввод группы с клавиатуры

### ISSUE THREAD

**Issue by 0niel** [Ninja-Official/rtu-mirea-mobile#58]
**Проблема**
Из отзыва в Play Market: "При вводе номера группы раскладка с цифр автоматически меняется на буквы, так что ввод группы занимает определенное время"

**Решение**
Оптимизировать ввод таким образом, чтобы не менялась раскладка, а также чтобы знак "-" ставился автоматически.

**Comment by 0niel** [comment]
Частично исправлено в #60 , но тип клавиатуры всё равно переключается из-за 
```
TextInputPlugin(20970): Composing region changed by the framework. Restarting the input method.
```
Нужно что-то придумать.

**Comment by ValeryVerkhoturov** [comment]
Добавить ограничение на количество символов
![92FDFC5F-6D4F-4E56-8564-556D6783E763](https://user-images.githubusercontent.com/70258211/131287247-0ce6485b-d4b6-4b7c-9c73-79e78997880a.png)
