### ISSUE TITLE
[FEATURE REQUEST] Автоматическое обновление расписания

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#59]
**Проблемы**
- Нет представления, подгружено расписание с сервера или из памяти устройства. 
- Не интуитивная реакция на нажатие на кнопку обновления расписания: 
- - мигает затемненный слева текст при удачном обновлении
- - при отсутствии Интернета нет ошибки или другой реакции о загрузке

**Решение**
- Обновлять расписание при входе в приложение. В случае неудачи подгрузить из памяти устройства, но пытаться загрузить и заменить старое на расписание из Интернета. 
- Убрать значок обновления расписания

**Альтернативы**
Изменять цвет значка обновления 
- удачная загрузка - белый, неудачная - красный
- удачная загрузка - серый, неудачная - белый

Скрывать значок обновления в случае удачной подгрузки с Интернета

**Comment by 0niel** [comment]
> Нет представления, подгружено расписание с сервера или из памяти устройства.

Проблема исправлена в #74 от @uSlashVlad, но считаю, что решение нужно дополнительно какое-то сообщение пользователю, так как цвет может быть не очень понятен.

**Comment by uSlashVlad** [comment]
Полагаю, что #71, #74 и #78 полностью закрывают все пункты данной фичи и поэтому думаю, что и задачу можно закрыть
