### ISSUE TITLE
[BUG] - уезжает номер аудитории

### ISSUE THREAD

**Issue by Delivery-Klad** [Ninja-Official/rtu-mirea-mobile#67]
**Описание ошибки**
Не видно номер аудитории, если название предмета слишком длинное.

**Скриншоты**
![image](https://user-images.githubusercontent.com/49003989/131610222-48744541-e253-4d03-b774-bb44434ecda2.png)

**Смартфон (пожалуйста, заполните следующую информацию):**
 - Девайс: iPhone7
 - OS: iOS14.7.1

**Comment by 0niel** [comment]
Исправлено в #68. Спасибо.
