### ISSUE TITLE
[FEATURE REQUEST] Сохранение состояния календаря

### ISSUE THREAD

**Issue by sermah** [Ninja-Official/rtu-mirea-mobile#70]
**Описание**
В приложении при переключении календаря (_Неделя -> Месяц -> 2 Недели_) последнее состояние не сохраняется. При перезапуске приложения приходится заново переключать календарь.

**Решение.**
Сделать так, чтобы последнее состояние переключателя сохранялось при выходе и восстанавливалось при входе в приложение.

![image](https://user-images.githubusercontent.com/40694307/131794707-a26ce7d5-7673-40f7-b004-c71d7b5b65e5.png)

**Comment by 0niel** [comment]
Реализовано в #71. Спасибо.
