### ISSUE TITLE
[BUG] Кнопки в разделе "О приложении" выходят за границу экрана

### ISSUE THREAD

**Issue by MadL1me** [Ninja-Official/rtu-mirea-mobile#76]
**Описание ошибки**
Кнопки Github и Telegramm слишком жирные, и выходят за границы экрана

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейти в "О приложении"

**Ожидаемое поведение**
Кнопки не выходят за границы экрана

**Скриншоты**
![image](https://user-images.githubusercontent.com/46647517/132078398-2462903d-7f66-42e3-84d5-07e6b1a6bc75.png)

**Смартфон:**
 - Девайс: iPhoneSE
 - OS: iOS 14.6

**Comment by 0niel** [comment]
Исправлено в #77 PR от @uSlashVlad
