### ISSUE TITLE
[FEATURE REQUEST] Изменение поведения дефиса в поле ввода группы

### ISSUE THREAD

**Issue by TinyClayMan** [Ninja-Official/rtu-mirea-mobile#85]
Необходимость удалять дефис для пользователя является излишней.
Предложение: изменить поле ввода так, чтобы при удалении последнего символа, являющегося пятым или седьмым в поле ввода, вместе с ним удалялся бы и дефис, разделяющий код группы и её номер или номер группы и год зачисления. Либо изменить отображение поля ввода так, чтобы вместо одной строки было несколько элементов под каждую букву и цифру группы, со статичными дефисами после четвертого и шестого элементов (это решение также вводит лимит на количество введённых символов).

Пример:

1. "ИКБО-12-3" – при удалении тройки удалится и дефис (и в поле ввода останется "ИКБО-12")
2. "И К Б _ - _ _ - _ _" – частично пустое поле ввода из второго предложенного решения

**Comment by ValeryVerkhoturov** [comment]
#58

**Comment by TinyClayMan** [comment]
> Дубликат #58

Там речь идёт об автоматическом добавлении дефиса и смене раскладки, здесь – об автоматическом убирании дефиса или разбиения строки ввода на отдельные элементы. Дублирования нет.
