### ISSUE TITLE
[BUG] Артефакты отрисовки пиктограм при большом масштабе карты

### ISSUE THREAD

**Issue by BearPro** [Ninja-Official/rtu-mirea-mobile#89]
**Описание ошибки**
Неограниченное масштабирование карты позволяет наблюдать артефакты при отрисовке пиктограм при большом масштабе.

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейдите на вкладку карты
2. Сильно увеличивайте масштаб, так чтобы край символа или иконки продолжал оставаться в кадре.

**Ожидаемое поведение**
Масштабирование ограничено, так сильно приблизить карту нельзя.

**Запись экрана**

https://user-images.githubusercontent.com/13729660/132410169-f73abb74-bbd8-457c-9144-8c60978cbcff.mp4

**Смартфон**
 - Девайс: OnePlus Nord какой-то
 - OS: Android 11
 - Браузер: Firefox
 - Версия 1.0.1

**Comment by MadL1me** [comment]
@BearPro бесконечное масштабирование было пофикшено в #55
