### ISSUE TITLE
[BUG] Некорректное отображение процента масштаба

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-mobile#94]
**Описание ошибки**
Дефолтный масштаб 11%
Максимальное отдаление 0%
Максимальное приближение 100%

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейдите в раздел Карта
2. Смотреть ошибку
3. Максимально отдалить карту
4. Смотреть ошибку
5. Максимально приблизить карту
6. Смотреть ошибку

**Ожидаемое поведение**
Дефолтный масштаб 100% (карту видно целиком)
100% > макс. отдаление >= 1%
Макс. приближение > 100%

**Смартфон:**
Девайс: iPad

**Comment by MadL1me** [comment]
@ValeryVerkhoturov я так понимаю тебе циферки не нравятся? Какой цифрой тогда должно быть макс отдаление?

**Comment by ValeryVerkhoturov** [comment]
> @ValeryVerkhoturov я так понимаю тебе циферки не нравятся? Какой цифрой тогда должно быть макс отдаление?

Дополнил. Суммарное расстояние от карты до краев устройства = секущей карты

**Comment by ValeryVerkhoturov** [comment]
> @ValeryVerkhoturov я так понимаю тебе циферки не нравятся? Какой цифрой тогда должно быть макс отдаление?

Как в релизе 100%

**Comment by ValeryVerkhoturov** [comment]
+- погрешность на красивое число 1, 5, 10, 20
